/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionLog: typeof import('./src/components/editableTable/actionLog.vue')['default']
    AiAssistant: typeof import('./src/components/aiAssistant/index.vue')['default']
    AiScreenshotList: typeof import('./src/components/aiAssistant/AiScreenshotList.vue')['default']
    AntdxChatArea: typeof import('./src/components/aiAssistant/antdxChatArea.vue')['default']
    BatchAdd: typeof import('./src/components/editableTable/batchAdd.vue')['default']
    ChangePassword: typeof import('./src/components/common/changePassword.vue')['default']
    ChangePrinterAndLabel: typeof import('./src/components/common/changePrinterAndLabel.vue')['default']
    ChcTable: typeof import('./src/components/chcTable/index.vue')['default']
    ChooseInstitutionAndWarehouse: typeof import('./src/components/common/chooseInstitutionAndWarehouse.vue')['default']
    Cropper: typeof import('./src/components/cropper/src/cropper.vue')['default']
    CropperAvatar: typeof import('./src/components/cropper/src/cropper-avatar.vue')['default']
    CropperModal: typeof import('./src/components/cropper/src/cropper-modal.vue')['default']
    EditableTable: typeof import('./src/components/editableTable/editableTable.vue')['default']
    ForcePasswordChangeModal: typeof import('./src/components/force-password-change-modal/index.vue')['default']
    Page: typeof import('./src/components/spd/page/index.vue')['default']
    PageInnerTabs: typeof import('./src/components/spd/page/pageInnerTabs.vue')['default']
    RecordBtn: typeof import('./src/components/aiAssistant/recordBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowAntdX: typeof import('./src/components/ai-scpAssistant/rowAntdX.vue')['default']
    RowTDchat: typeof import('./src/components/ai-scpAssistant/rowTDchat.vue')['default']
    SpdPageNew: typeof import('./src/components/spd/page/spdPageNew.vue')['default']
    Src: typeof import('./src/components/spd/KeepAliveIframe/src/index.vue')['default']
    Sso: typeof import('./src/components/sso/sso/index.vue')['default']
    SsoLogin: typeof import('./src/components/sso/ssoLogin/index.vue')['default']
    Summarize: typeof import('./src/components/spd/summarize/index.vue')['default']
    TdChatArea: typeof import('./src/components/aiAssistant/tdChatArea.vue')['default']
    ViewMessageModal: typeof import('./src/components/common/viewMessageModal.vue')['default']
  }
}
