import { addIcon } from '@vben-core/icons';

import antdInboundProductSearch from '@iconify/icons-ant-design/align-left-outlined';
import antAppstoreOutlined from '@iconify/icons-ant-design/appstore-outlined';
import antdBankOutlined from '@iconify/icons-ant-design/bank-outlined';
import antdWorkStation from '@iconify/icons-ant-design/block-outlined';
import antBookOutlined from '@iconify/icons-ant-design/book-outlined';
import antdAddressRouteConfig from '@iconify/icons-ant-design/border-verticle-outlined';
import antdBoxPlot from '@iconify/icons-ant-design/box-plot-outlined';
import antdBranchesOutlined from '@iconify/icons-ant-design/branches-outlined';
import antdShipmentUpload from '@iconify/icons-ant-design/carry-out-outlined';
import antdCheckSquare from '@iconify/icons-ant-design/check-square-outlined';
import antClockCircleOutlined from '@iconify/icons-ant-design/clock-circle-outlined';
import antdDockCar from '@iconify/icons-ant-design/column-width-outlined';
import antdContactsOutlined from '@iconify/icons-ant-design/contacts-outlined';
import antdInboundNotice from '@iconify/icons-ant-design/container-outlined';
import antdContainerTwotone from '@iconify/icons-ant-design/container-twotone';
import antdRouteAddress from '@iconify/icons-ant-design/dash-outlined';
import antdDropboxSquareFilled from '@iconify/icons-ant-design/dropbox-square-filled';
import antFileAddOutlined from '@iconify/icons-ant-design/file-add-outlined';
import antdFileDoneOutlined from '@iconify/icons-ant-design/file-done-outlined';
import antdRejectionSlipPrint from '@iconify/icons-ant-design/file-excel-outlined';
import antdPutawayRejectPrint from '@iconify/icons-ant-design/file-ppt-outlined';
import antdInboundNreceive from '@iconify/icons-ant-design/file-protect-outlined';
import antdInboundQueryProcess from '@iconify/icons-ant-design/file-search-outlined';
import antdFileTextOutlined from '@iconify/icons-ant-design/file-text-outlined';
import antdPickListManagement from '@iconify/icons-ant-design/file-word-outlined';
import antdlotAttach from '@iconify/icons-ant-design/file-zip-outlined';
import antdInboundLineTemp from '@iconify/icons-ant-design/filter-outlined';
import antdExportOutlined from '@iconify/icons-ant-design/export-outlined';
import antdInboundNoticeGui from '@iconify/icons-ant-design/fund-outlined';
import antdDisConfig from '@iconify/icons-ant-design/group-outlined';
import antdDisLocationConfig from '@iconify/icons-ant-design/hdd-outlined';
import antdHome from '@iconify/icons-ant-design/home-outlined';
import antdDevice from '@iconify/icons-ant-design/layout-outlined';
import antLoginOutlined from '@iconify/icons-ant-design/login-outlined';
import antMedicineBoxOutlined from '@iconify/icons-ant-design/medicine-box-outlined';
import antdReturnConfig from '@iconify/icons-ant-design/menu-fold-outlined';
import antdWorkCheck from '@iconify/icons-ant-design/monitor-outlined';
import antdInboundNreceiveGui from '@iconify/icons-ant-design/node-expand-outlined';
import antNotificationOutlined from '@iconify/icons-ant-design/notification-outlined';
import antOrderedListOutlined from '@iconify/icons-ant-design/ordered-list-outlined';
import antdBoxPlotScatter from '@iconify/icons-ant-design/pic-center-outlined';
import antdInspectionFormPrint from '@iconify/icons-ant-design/profile-outlined';
import antdProductCheck from '@iconify/icons-ant-design/project-outlined';
import antdInboundAdjust from '@iconify/icons-ant-design/rotate-right-outlined';
import antdSafetyCertificateOutlined from '@iconify/icons-ant-design/safety-certificate-outlined';
import antdSchedule from '@iconify/icons-ant-design/schedule-outlined';
import antdInboundQuery from '@iconify/icons-ant-design/search-outlined';
import antSecurityScanOutlined from '@iconify/icons-ant-design/security-scan-outlined';
import antdInboundNoticeSearch from '@iconify/icons-ant-design/select-outlined';
import antSettingOutlined from '@iconify/icons-ant-design/setting-outlined';
import antShareAltOutlined from '@iconify/icons-ant-design/share-alt-outlined';
import antDesignSplitcellsOutlined from '@iconify/icons-ant-design/split-cells-outlined';
import antdContainerTypeConfig from '@iconify/icons-ant-design/switcher-outlined';
import antdContainerConfig from '@iconify/icons-ant-design/tablet-outlined';
import antdEmployeearea from '@iconify/icons-ant-design/team-outlined';
import antdUpSquareOutlined from '@iconify/icons-ant-design/up-square-outlined';
import antUserOutlined from '@iconify/icons-ant-design/user-outlined';
import antdPicChange from '@iconify/icons-ant-design/vertical-left-outlined';
import antdWalletOutlined from '@iconify/icons-ant-design/wallet-outlined';
import antdWareSearch from '@iconify/icons-ant-design/zoom-in-outlined';
import bxBxlReact from '@iconify/icons-bx/bxl-react';
import assetConfirm from '@iconify/icons-carbon/asset-confirm';
import carbonAssetView from '@iconify/icons-carbon/asset-view';
import autoscaling from '@iconify/icons-carbon/autoscaling';
import barcode from '@iconify/icons-carbon/barcode';
import carbonBatchJob from '@iconify/icons-carbon/batch-job';
import buildTool from '@iconify/icons-carbon/build-tool';
import certificateCheck from '@iconify/icons-carbon/certificate-check';
import carbonChangeCatalog from '@iconify/icons-carbon/change-catalog';
import chartBar from '@iconify/icons-carbon/chart-bar';
import chartBarFloating from '@iconify/icons-carbon/chart-bar-floating';
import chartBarOverlay from '@iconify/icons-carbon/chart-bar-overlay';
import chartBarStacked from '@iconify/icons-carbon/chart-bar-stacked';
import chartBarTarget from '@iconify/icons-carbon/chart-bar-target';
import chartRelationship from '@iconify/icons-carbon/chart-relationship';
import chartWaterfall from '@iconify/icons-carbon/chart-waterfall';
import carbonChat from '@iconify/icons-carbon/chat';
import cloudMonitoring from '@iconify/icons-carbon/cloud-monitoring';
import carbonDataBackup from '@iconify/icons-carbon/data-backup';
import dataCheck from '@iconify/icons-carbon/data-check';
import carbonDataViewAlt from '@iconify/icons-carbon/data-view-alt';
import delivery from '@iconify/icons-carbon/delivery';
import carbonDeliveryTruck from '@iconify/icons-carbon/delivery-truck';
import carbonDocument from '@iconify/icons-carbon/document';
import carbonDocumentAdd from '@iconify/icons-carbon/document-add';
import documentSigned from '@iconify/icons-carbon/document-signed';
import carbonDocumentTasks from '@iconify/icons-carbon/document-tasks';
import carbonDocumentView from '@iconify/icons-carbon/document-view';
import carbonEdit from '@iconify/icons-carbon/edit';
import expandCategories from '@iconify/icons-carbon/expand-categories';
import carbonFileStorage from '@iconify/icons-carbon/file-storage';
import hospital from '@iconify/icons-carbon/hospital';
import carbonHospitalBed from '@iconify/icons-carbon/hospital-bed';
import hotel from '@iconify/icons-carbon/hotel';
import ibmEventStreams from '@iconify/icons-carbon/ibm-event-streams';
import ibmWatsonQuery from '@iconify/icons-carbon/ibm-watson-query';
import inventoryManagement from '@iconify/icons-carbon/inventory-management';
import label from '@iconify/icons-carbon/label';
import carbonLicenseMaintenance from '@iconify/icons-carbon/license-maintenance';
import list from '@iconify/icons-carbon/list';
import listChecked from '@iconify/icons-carbon/list-checked';
import listCheckedMirror from '@iconify/icons-carbon/list-checked-mirror';
import carbonLogoGithub from '@iconify/icons-carbon/logo-github';
import carbonMicroservices2 from '@iconify/icons-carbon/microservices-2';
import orderDetails from '@iconify/icons-carbon/order-details';
import carbonPackage from '@iconify/icons-carbon/package';
import plan from '@iconify/icons-carbon/plan';
import portOutput from '@iconify/icons-carbon/port-output';
import propertyRelationship from '@iconify/icons-carbon/property-relationship';
import carbonQuery from '@iconify/icons-carbon/query';
import queryQueue from '@iconify/icons-carbon/query-queue';
import carbonQueued from '@iconify/icons-carbon/queued';
import recording from '@iconify/icons-carbon/recording';
import report from '@iconify/icons-carbon/report';
import carbonResult from '@iconify/icons-carbon/result';
import review from '@iconify/icons-carbon/review';
import carbonSearchLocate from '@iconify/icons-carbon/search-locate';
import carbonSearchLocateMirror from '@iconify/icons-carbon/search-locate-mirror';
import settingsAdjust from '@iconify/icons-carbon/settings-adjust';
import shoppingCart from '@iconify/icons-carbon/shopping-cart';
import shoppingCartArrowDown from '@iconify/icons-carbon/shopping-cart-arrow-down';
import shoppingCartError from '@iconify/icons-carbon/shopping-cart-error';
import shoppingCartPlus from '@iconify/icons-carbon/shopping-cart-plus';
import spellCheck from '@iconify/icons-carbon/spell-check';
import carbonStamp from '@iconify/icons-carbon/stamp';
import carbonSun from '@iconify/icons-carbon/sun';
import carbonTaskApproved from '@iconify/icons-carbon/task-approved';
import carbonTaskView from '@iconify/icons-carbon/task-view';
import carbonTextLongParagraph from '@iconify/icons-carbon/text-long-paragraph';
import carbonToolBox from '@iconify/icons-carbon/tool-box';
import carbonTrashCan from '@iconify/icons-carbon/trash-can';
import carbonUserFollow from '@iconify/icons-carbon/user-follow';
import carbonUserRole from '@iconify/icons-carbon/user-role';
import carbonWarning from '@iconify/icons-carbon/warning';
import carbonWarningOther from '@iconify/icons-carbon/warning-other';
import carbonWorkflowAutomation from '@iconify/icons-carbon/workflow-automation';
import carbonWorkspace from '@iconify/icons-carbon/workspace';
import eosApiOutlined from '@iconify/icons-eos-icons/api-outlined';
import eosClusterManagement from '@iconify/icons-eos-icons/cluster-management';
import eosPackageOutlined from '@iconify/icons-eos-icons/package-outlined';
import flunetMdlDocumentApproval from '@iconify/icons-fluent-mdl2/document-approval';
import fluentMd2Processing from '@iconify/icons-fluent-mdl2/processing';
import flunetMdlProcessingRun from '@iconify/icons-fluent-mdl2/processing-run';
import fluentMdlProduct from '@iconify/icons-fluent-mdl2/product';
import fluentMd2ProductRelease from '@iconify/icons-fluent-mdl2/product-release';
import fluentArchiveArrowBack from '@iconify/icons-fluent/archive-arrow-back-24-regular';
import fluentBoxSearch16Regular from '@iconify/icons-fluent/box-search-16-regular';
import icBaselineMessage from '@iconify/icons-ic/baseline-message';
import baselinePersonSearch from '@iconify/icons-ic/baseline-person-search';
import icOutlineLogOut from '@iconify/icons-ic/outline-log-out';
import iconParkOutlineAssociation from '@iconify/icons-icon-park-outline/association';
import iconParkOutlineConsume from '@iconify/icons-icon-park-outline/consume';
import DocSearchTwo from '@iconify/icons-icon-park-outline/doc-search-two';
import iconParkOutlineHistoryQuery from '@iconify/icons-icon-park-outline/history-query';
import lucideAlignHorizontalSpaceBetween from '@iconify/icons-lucide/align-horizontal-space-between';
import lucideAreaChart from '@iconify/icons-lucide/area-chart';
import lucideBell from '@iconify/icons-lucide/bell';
import lucideBookCheck from '@iconify/icons-lucide/book-check';
import lucideBookCopy from '@iconify/icons-lucide/book-copy';
import lucideBookOpen from '@iconify/icons-lucide/book-open';
import lucideBookOpenText from '@iconify/icons-lucide/book-open-text';
import lucideBookPlus from '@iconify/icons-lucide/book-plus';
import lucideBookText from '@iconify/icons-lucide/book-text';
import lucideBookUp from '@iconify/icons-lucide/book-up';
import lucideBoxes from '@iconify/icons-lucide/boxes';
import lucideCalendarCheck from '@iconify/icons-lucide/calendar-check';
import lucideClipboardList from '@iconify/icons-lucide/clipboard-list';
import lucideClipboardPaste from '@iconify/icons-lucide/clipboard-paste';
import lucideExternalLink from '@iconify/icons-lucide/external-link';
import lucideEye from '@iconify/icons-lucide/eye';
import lucideFileCheck from '@iconify/icons-lucide/file-check';
import lucideFileDown from '@iconify/icons-lucide/file-down';
import lucideFileInput from '@iconify/icons-lucide/file-input';
import lucideFilePlus from '@iconify/icons-lucide/file-plus';
import lucideFileSearch from '@iconify/icons-lucide/file-search';
import lucideFileSearch2 from '@iconify/icons-lucide/file-search-2';
import lucideFileUp from '@iconify/icons-lucide/file-up';
import lucideFiles from '@iconify/icons-lucide/files';
import lucideGitFork from '@iconify/icons-lucide/git-fork';
import lucideLayoutDashboard from '@iconify/icons-lucide/layout-dashboard';
import lucideLayoutPanelLeft from '@iconify/icons-lucide/layout-panel-left';
import lucideLogOut from '@iconify/icons-lucide/log-out';
import lucidePackage from '@iconify/icons-lucide/package';
import lucidePackageCheck from '@iconify/icons-lucide/package-check';
import lucidePackageOpen from '@iconify/icons-lucide/package-open';
import lucidePackagePlus from '@iconify/icons-lucide/package-plus';
import lucidePackageSearch from '@iconify/icons-lucide/package-search';
import lucidePrinter from '@iconify/icons-lucide/printer';
import lucideSearchCode from '@iconify/icons-lucide/search-code';
import lucideSettings2 from '@iconify/icons-lucide/settings-2';
import lucideUpload from '@iconify/icons-lucide/upload';
import lucideWarehouse from '@iconify/icons-lucide/warehouse';
import majesticonsExtensivePrescription from '@iconify/icons-majesticons/script-prescription';
import calendarMonthOutline from '@iconify/icons-material-symbols/calendar-month-outline';
import materialSymbolsContract from '@iconify/icons-material-symbols/contract';
import ContractEdit from '@iconify/icons-material-symbols/contract-edit';
import materialSymbolsFactCheck from '@iconify/icons-material-symbols/fact-check';
import materialSymbolsInput from '@iconify/icons-material-symbols/input';
import materialScanDeleteOutline from '@iconify/icons-material-symbols/scan-delete-outline';
import materialSummarizeOutline from '@iconify/icons-material-symbols/summarize-outline';
import materialSurgicalOutline from '@iconify/icons-material-symbols/surgical-outline';
import warehouseOutline from '@iconify/icons-material-symbols/warehouse-outline';
import mdiAccountCashOutline from '@iconify/icons-mdi/account-cash-outline';
import mdiAccountCog from '@iconify/icons-mdi/account-cog';
import mdiAccountStar from '@iconify/icons-mdi/account-star';
import mdiBarrel from '@iconify/icons-mdi/barrel';
import mdiBriefcaseCheck from '@iconify/icons-mdi/briefcase-check';
import mdiBriefcaseClock from '@iconify/icons-mdi/briefcase-clock';
import mdiBriefcaseSearch from '@iconify/icons-mdi/briefcase-search';
import mdiChartBar from '@iconify/icons-mdi/chart-bar';
import mdiClipboardSearch from '@iconify/icons-mdi/clipboard-search';
import mdiContract from '@iconify/icons-mdi/contract';
import mdicCurrencyBrl from '@iconify/icons-mdi/currency-brl';
import mdiCurrencyUsd from '@iconify/icons-mdi/currency-usd';
import mdiFileClockOutline from '@iconify/icons-mdi/file-clock-outline';
import mdiFileDocumentCheck from '@iconify/icons-mdi/file-document-check';
import mdiFileDocumentCheckOutline from '@iconify/icons-mdi/file-document-check-outline';
import mdiFileDocumentEdit from '@iconify/icons-mdi/file-document-edit';
import mdiFileDocumentEditOutline from '@iconify/icons-mdi/file-document-edit-outline';
import mdiFileDocumentMultiple from '@iconify/icons-mdi/file-document-multiple';
import mdiFileEye from '@iconify/icons-mdi/file-eye';
import mdiFileLock from '@iconify/icons-mdi/file-lock';
import mdiFileLockOpen from '@iconify/icons-mdi/file-lock-open';
import mdiFileSign from '@iconify/icons-mdi/file-sign';
import mdiFileTable from '@iconify/icons-mdi/file-table';
import mdiFinance from '@iconify/icons-mdi/finance';
import mdiNewbox from '@iconify/icons-mdi/new-box';
import mdiOfficeBuildingMarker from '@iconify/icons-mdi/office-building-marker';
import mdiPackageVariantClosedPlus from '@iconify/icons-mdi/package-variant-closed-plus';
import mdiPackageVariantPlus from '@iconify/icons-mdi/package-variant-plus';
import mdiReceiptTextOutline from '@iconify/icons-mdi/receipt-text-outline';
import mdiReceiptTextSend from '@iconify/icons-mdi/receipt-text-send';
import mdiSwapHorizontalVariant from '@iconify/icons-mdi/swap-horizontal-variant';
import mdiTagEditOutline from '@iconify/icons-mdi/tag-edit-outline';
import mdiWorkflow from '@iconify/icons-mdi/workflow';
import phCertificateLight from '@iconify/icons-ph/certificate-light';
import tablerZoomMoney from '@iconify/icons-tabler/zoom-money';
import antdWindowsOutlined from '@iconify/icons-ant-design/windows-outlined';
import antdFolderOpenTwotone from '@iconify/icons-ant-design/folder-open-twotone';
import antdBarcodeOutlined from '@iconify/icons-ant-design/barcode-outlined';
import carbonSearch from '@iconify/icons-carbon/search';
import lucideTable2 from '@iconify/icons-lucide/table-2';
import carbonChartBarTarget from '@iconify/icons-carbon/chart-bar-target';
import carbonBuildingInsights1 from '@iconify/icons-carbon/building-insights-1';
import carbonTextLink from '@iconify/icons-carbon/text-link';
/**
 * 这里添加菜单图标
 */

// addIcon('eos-icons:system-group', SystemGroup);
// addIcon('ph:user-duotone', UserDuotone);
// addIcon('ant-design:user-outlined', UserAntd);
// addIcon('eos-icons:role-binding-outlined', RoleBindingOutlined);
// addIcon('ic:sharp-menu', MenuSharp);
// addIcon('mingcute:department-line', DepartmentLine);
// addIcon('icon-park-outline:appointment', Appointment);
// addIcon('fluent-mdl2:dictionary', Dictionary);
// addIcon('icon-park-twotone:setting-two', SettingTwo);
// addIcon('fe:notice-push', NoticePush);
// addIcon('material-symbols:logo-dev-outline', LogoDevOutline);
// addIcon('arcticons:one-hand-operation', Operation);
// addIcon(
//   'streamline:interface-login-dial-pad-finger-password-dial-pad-dot-finger',
//   InterfaceLoginDialPadFingerPasswordDialPadDotFinger,
// );
// addIcon('solar:folder-with-files-outline', FolderWithFilesOutline);
// addIcon('simple-icons:authy', Authy);
// addIcon('solar:monitor-smartphone-outline', monitorPhoneOutlined);
// addIcon('ic:baseline-house', BaseLineHouse);
// addIcon('ph:users-light', users);
// addIcon('bi:houses-fill', BaseLineHousesFill);
// addIcon('ph:user-list', userList);
// addIcon('bx:package', BxPackage);
// addIcon('solar:monitor-bold-duotone', monitorBoldDuotone);
// addIcon('solar:monitor-camera-outline', monitorCameraOutlined);
// addIcon('material-symbols:generating-tokens-outline', generatingTokensOutline);
// addIcon('devicon:redis-wordmark', redisWordmark);
// addIcon('devicon:spring-wordmark', springWordmark);
// addIcon('akar-icons:schedule', schedule);
// addIcon('mdi:tools', tools);
// addIcon('ant-design:tool-outlined', antdTool);
// addIcon('tabler:code', code);
// addIcon('flat-color-icons:plus', plus);
// addIcon('devicon:vscode', vscode);
// addIcon('lucide:table', table);
// addIcon('emojione:evergreen-tree', evergreenTree);
// addIcon('fluent-mdl2:leave-user', leaveUser);
// addIcon('mdi:workflow-outline', workflowOutline);
// addIcon('tabler:category-plus', categoryPlus);
// addIcon('carbon:model-alt', modelAlt);
// addIcon('fluent-mdl2:build-definition', builDefinition);
// addIcon('fluent-mdl2:build-definition', builDefinition);
// addIcon('icon-park-outline:monitor', monitor);
// addIcon('ri:instance-line', insatnceLine);
// addIcon('ri:todo-line', todoLine);
// addIcon('fluent:form-24-regular', from24);
// addIcon('carbon:task-approved', taskApproved);
// addIcon('ic:round-launch', roundLaunch);
// addIcon('material-symbols:cloud-done-outline-rounded', cloudDoneOutlineRounded);
// addIcon('mdi:cc-outline', ccOutline);
// addIcon('lucide:book-open-text', boolOpenText);
// addIcon('lucide:copyright', copyright);

// // 个人中心
// addIcon('mingcute:profile-line', profileLine);
// // oss配置
// addIcon('ant-design:setting-outlined', settingOutline);
// // 请假
// addIcon('flat-color-icons:leave', leave);
// // flow
// addIcon('fluent-mdl2:flow', flow);
// 库存管理

// 新增本地图标
addIcon('bx:bxl-react', bxBxlReact);
addIcon('carbon:workspace', carbonWorkspace);
addIcon('lucide:layout-dashboard', lucideLayoutDashboard);
addIcon('lucide:area-chart', lucideAreaChart);
addIcon('mdi:barrel', mdiBarrel);
addIcon('carbon:logo-github', carbonLogoGithub);

addIcon('ant-design:home-outlined', antdHome);
addIcon('ant-design:layout-outlined', antdDevice);
addIcon('ant-design:block-outlined', antdWorkStation);
addIcon('ant-design:column-width-outlined', antdDockCar);
addIcon('ant-design:check-square-outlined', antdCheckSquare);
addIcon('ant-design:box-plot-outlined', antdBoxPlot);
addIcon('ant-design:pic-center-outlined', antdBoxPlotScatter);
addIcon('ant-design:vertical-left-outlined', antdPicChange);
addIcon('ant-design:menu-fold-outlined', antdReturnConfig);
addIcon('ant-design:wallet-outlined', antdWalletOutlined);
addIcon('ant-design:group-outlined', antdDisConfig);
addIcon('ant-design:hdd-outlined', antdDisLocationConfig);
addIcon('ant-design:tablet-outlined', antdContainerConfig);
addIcon('ant-design:switcher-outlined', antdContainerTypeConfig);
addIcon('ant-design:border-verticle-outlined', antdAddressRouteConfig);
addIcon('ant-design:dash-outlined', antdRouteAddress);
addIcon('ant-design:team-outlined', antdEmployeearea);
addIcon('ant-design:schedule-outlined', antdSchedule);
addIcon('ant-design:search-outlined', antdInboundQuery);
addIcon('ant-design:file-search-outlined', antdInboundQueryProcess);
addIcon('ant-design:container-outlined', antdInboundNotice);
addIcon('ant-design:fund-outlined', antdInboundNoticeGui);
addIcon('ant-design:rotate-right-outlined', antdInboundAdjust);
addIcon('ant-design:select-outlined', antdInboundNoticeSearch);
addIcon('ant-design:filter-outlined', antdInboundLineTemp);
addIcon('ant-design:file-zip-outlined', antdlotAttach);
addIcon('ant-design:file-protect-outlined', antdInboundNreceive);
addIcon('ant-design:node-expand-outlined', antdInboundNreceiveGui);
addIcon('ant-design:carry-out-outlined', antdShipmentUpload);
addIcon('ant-design:monitor-outlined', antdWorkCheck);
addIcon('ant-design:project-outlined', antdProductCheck);
addIcon('ant-design:zoom-in-outlined', antdWareSearch);
addIcon('ant-design:profile-outlined', antdInspectionFormPrint);
addIcon('ant-design:file-excel-outlined', antdRejectionSlipPrint);
addIcon('ant-design:file-word-outlined', antdPickListManagement);
addIcon('ant-design:file-ppt-outlined', antdPutawayRejectPrint);
addIcon('ant-design:align-left-outlined', antdInboundProductSearch);
addIcon('ant-design:contacts-outlined', antdContactsOutlined);
addIcon(
  'ant-design:safety-certificate-outlined',
  antdSafetyCertificateOutlined,
);
addIcon('ant-design:up-square-outlined', antdUpSquareOutlined);
addIcon('ant-design:file-text-outlined', antdFileTextOutlined);
addIcon('ant-design:branches-outlined', antdBranchesOutlined);
addIcon('ant-design:file-done-outlined', antdFileDoneOutlined);
addIcon('ant-design:container-twotone', antdContainerTwotone);

addIcon('carbon:port-output', portOutput);
addIcon('carbon:plan', plan);
addIcon('carbon:asset-confirm', assetConfirm);
addIcon('carbon:autoscaling', autoscaling);
addIcon('carbon:cloud-monitoring', cloudMonitoring);
addIcon('carbon:order-details', orderDetails);
addIcon('carbon:label', label);
addIcon('carbon:shopping-cart-error', shoppingCartError);
addIcon('carbon:delivery', delivery);
addIcon('carbon:report', report);
addIcon('carbon:list', list);
addIcon('carbon:shopping-cart', shoppingCart);
addIcon('carbon:review', review);
addIcon('carbon:document-signed', documentSigned);
addIcon('carbon:barcode', barcode);
addIcon('carbon:shopping-cart-arrow-down', shoppingCartArrowDown);
addIcon('carbon:chart-waterfall', chartWaterfall);
addIcon('carbon:certificate-check', certificateCheck);
addIcon('carbon:shopping-cart-plus', shoppingCartPlus);
addIcon('carbon:chart-relationship', chartRelationship);
addIcon('carbon:property-relationship', propertyRelationship);
addIcon('carbon:settings-adjust', settingsAdjust);
addIcon('carbon:query-queue', queryQueue);
addIcon('carbon:data-check', dataCheck);
addIcon('carbon:recording', recording);
addIcon('carbon:inventory-management', inventoryManagement);
addIcon('carbon:ibm-watson-query', ibmWatsonQuery);
addIcon('carbon:build-tool', buildTool);
addIcon('carbon:hospital', hospital);
addIcon('carbon:ibm-event-streams', ibmEventStreams);
addIcon('carbon:expand-categories', expandCategories);
addIcon('carbon:chart-bar', chartBar);
addIcon('carbon:list-checked', listChecked);
addIcon('carbon:list-checked-mirror', listCheckedMirror);
addIcon('carbon:spell-check', spellCheck);
addIcon('carbon:chart-bar-floating', chartBarFloating);
addIcon('carbon:chart-bar-overlay', chartBarOverlay);
addIcon('carbon:chart-bar-stacked', chartBarStacked);
addIcon('carbon:chart-bar-target', chartBarTarget);
addIcon('ant-design:bank-outlined', antdBankOutlined);
addIcon('ant-design:dropbox-square-filled', antdDropboxSquareFilled);
addIcon('carbon:hotel', hotel);
addIcon('ant-design:container-outlined', antdInboundNotice);
addIcon('ant-design:ordered-list-outlined', antOrderedListOutlined);
addIcon('ant-design:book-outlined', antBookOutlined);
addIcon('ant-design:login-outlined', antLoginOutlined);
addIcon('eos-icons:login-outlined', eosPackageOutlined);
addIcon('carbon:task-approved', carbonTaskApproved);
addIcon('mdi:swap-horizontal-variant', mdiSwapHorizontalVariant);
addIcon('ant-design:file-add-outlined', antFileAddOutlined);
addIcon('ant-design:appstore-outlined', antAppstoreOutlined);
addIcon('fluent-mdl2:document-approval', flunetMdlDocumentApproval);
addIcon('ant-design:security-scan-outlined', antSecurityScanOutlined);
addIcon('carbon:batch-job', carbonBatchJob);
addIcon('fluent-mdl2:processing-run', flunetMdlProcessingRun);
addIcon('material-symbols:scan-delete-outline', materialScanDeleteOutline);
addIcon('fluent:archive-arrow-back-24-regular', fluentArchiveArrowBack);
addIcon('lucide:calendar-check', lucideCalendarCheck);
addIcon('ant-design:medicine-box-outlined', antMedicineBoxOutlined);
addIcon('fluent-mdl2:product', fluentMdlProduct);
addIcon('ant-design:setting-outlined', antSettingOutlined);
addIcon('carbon:tool-box', carbonToolBox);
addIcon('mdi:package-variant-closed-plus', mdiPackageVariantClosedPlus);
addIcon('mdi:package-variant-plus', mdiPackageVariantPlus);
addIcon('carbon:package', carbonPackage);
addIcon('lucide:package-search', lucidePackageSearch);
addIcon('ic:outline-log-out', icOutlineLogOut);
addIcon('lucide:log-out', lucideLogOut);
addIcon('lucide:package', lucidePackage);
addIcon('carbon:search-locate', carbonSearchLocate);
addIcon('carbon:search-locate-mirror', carbonSearchLocateMirror);
addIcon('lucide:file-search', lucideFileSearch);
addIcon('carbon:package', carbonPackage);
addIcon('carbon:warning-other', carbonWarningOther);
addIcon('carbon:warning', carbonWarning);
addIcon('carbon:edit', carbonEdit);
addIcon('lucide:search-code', lucideSearchCode);
addIcon('carbon:document-add', carbonDocumentAdd);
addIcon('carbon:file-storage', carbonFileStorage);
addIcon('carbon:document-tasks', carbonDocumentTasks);
addIcon('carbon:document-view', carbonDocumentView);
addIcon('lucide:book-up', lucideBookUp);
addIcon('lucide:book-plus', lucideBookPlus);
addIcon('lucide:book-check', lucideBookCheck);
addIcon('lucide:book-open', lucideBookOpen);
addIcon('lucide:book-open-text', lucideBookOpenText);
addIcon('lucide:book-copy', lucideBookCopy);
addIcon('lucide:file-input', lucideFileInput);
addIcon('lucide:file-up', lucideFileUp);
addIcon('lucide:file-check', lucideFileCheck);
addIcon('lucide:file-search', lucideFileSearch);
addIcon('lucide:file-search-2', lucideFileSearch2);
addIcon('lucide:files', lucideFiles);
addIcon('lucide:warehouse', lucideWarehouse);
addIcon('lucide:package-open', lucidePackageOpen);
addIcon('lucide:package-plus', lucidePackagePlus);
addIcon('lucide:boxes', lucideBoxes);
addIcon('carbon:microservices-2', carbonMicroservices2);
addIcon('ant-design:split-cells-outlined', antDesignSplitcellsOutlined);
addIcon('lucide:layout-panel-left', lucideLayoutPanelLeft);
addIcon('lucide:package-check', lucidePackageCheck);
addIcon('lucide:external-link', lucideExternalLink);
addIcon('lucide:clipboard-list', lucideClipboardList);
addIcon('lucide:clipboard-paste', lucideClipboardPaste);
addIcon('lucide:book-text', lucideBookText);
addIcon('carbon:task-view', carbonTaskView);
addIcon('carbon:asset-view', carbonAssetView);
addIcon('lucide:printer', lucidePrinter);
addIcon('carbon:change-catalog', carbonChangeCatalog);
addIcon('lucide:file-plus', lucideFilePlus);
addIcon('lucide:file-down', lucideFileDown);
addIcon('lucide:settings-2', lucideSettings2);
addIcon('ph:certificate-light', phCertificateLight);
addIcon('mdi:file-document-edit', mdiFileDocumentEdit);
addIcon('mdi:file-document-check', mdiFileDocumentCheck);
addIcon('mdi:file-document-multiple', mdiFileDocumentMultiple);
addIcon('proicons:clipboard-search', mdiClipboardSearch);
addIcon('mdi:file-lock-open', mdiFileLockOpen);
addIcon('mdi:file-lock', mdiFileLock);
addIcon('mdi:file-table', mdiFileTable);
addIcon('mdi:file-eye', mdiFileEye);
addIcon('mdi:office-building-marker', mdiOfficeBuildingMarker);
addIcon('mdi:briefcase-check', mdiBriefcaseCheck);
addIcon('mdi:briefcase-clock', mdiBriefcaseClock);
addIcon('mdi:briefcase-search', mdiBriefcaseSearch);
addIcon('material-symbols:contract-edit', ContractEdit);
addIcon('mdi:contract', mdiContract);
addIcon('material-symbols:contract', materialSymbolsContract);
addIcon('icon-park-outline:doc-search-two', DocSearchTwo);
addIcon('mdi:account-cog', mdiAccountCog);
addIcon('mdi:account-star', mdiAccountStar);
addIcon('ic:outline-person-search', baselinePersonSearch);
addIcon('mdi:chart-bar', mdiChartBar);
addIcon('mdi:new-box', mdiNewbox);
addIcon('lucide:package-search', lucidePackageSearch);
addIcon('icon-park-outline:association', iconParkOutlineAssociation);
addIcon('mdi:currency-usd', mdiCurrencyUsd);
addIcon('mdi:tag-edit-outline', mdiTagEditOutline);
addIcon('mdi:file-document-edit-outline', mdiFileDocumentEditOutline);
addIcon('mdi:account-cash-outline', mdiAccountCashOutline);
addIcon('mdi:file-document-check-outline', mdiFileDocumentCheckOutline);
addIcon('mdi:file-clock-outline', mdiFileClockOutline);
addIcon('tabler:zoom-money', tablerZoomMoney);
addIcon('material-symbols:warehouse-outline', warehouseOutline);
addIcon('material-symbols:calendar-month-outline', calendarMonthOutline);
addIcon('material-symbols:input', materialSymbolsInput);
addIcon('material-symbols:fact-check', materialSymbolsFactCheck);
addIcon('icon-park-outline:history-query', iconParkOutlineHistoryQuery);
addIcon('fluent-mdl2:processing', fluentMd2Processing);
addIcon('carbon:data-backup', carbonDataBackup);
addIcon('carbon:hospital-bed', carbonHospitalBed);
addIcon('carbon:sun', carbonSun);
addIcon('carbon:document', carbonDocument);
addIcon(
  'lucide:align-horizontal-space-between',
  lucideAlignHorizontalSpaceBetween,
);

addIcon('lucide:upload', lucideUpload);
addIcon('carbon:data-view-alt', carbonDataViewAlt);
addIcon('carbon:stamp', carbonStamp);
addIcon('carbon:delivery-truck', carbonDeliveryTruck);
addIcon('carbon:trash-can', carbonTrashCan);
addIcon('carbon:user-follow', carbonUserFollow);
addIcon('lucide:eye', lucideEye);
addIcon('carbon:chat', carbonChat);
addIcon('ant-design:share-alt-outlined', antShareAltOutlined);
addIcon('ant-design:user-outlined', antUserOutlined);
addIcon('carbon:user-role', carbonUserRole);
addIcon('material-symbols:surgical-outline', materialSurgicalOutline);
addIcon('ant-design:clock-circle-outlined', antClockCircleOutlined);
addIcon('ant-design:notification-outlined', antNotificationOutlined);
addIcon('carbon:queued', carbonQueued);
addIcon('ic:baseline-message', icBaselineMessage);
addIcon('eos-icons:api-outlined', eosApiOutlined);
addIcon('lucide:bell', lucideBell);
addIcon('carbon:text-long-paragraph', carbonTextLongParagraph);
addIcon('mdi:workflow', mdiWorkflow);
addIcon('carbon:workflow-automation', carbonWorkflowAutomation);
addIcon('mdi:receipt-text-outline', mdiReceiptTextOutline);
addIcon('mdi:finance', mdiFinance);
addIcon('material-symbols:summarize-outline', materialSummarizeOutline);
addIcon('mdi:currency-brl', mdicCurrencyBrl);
addIcon('lucide:git-fork', lucideGitFork);
addIcon('eos-icons:cluster-management', eosClusterManagement);
addIcon('carbon:license-maintenance', carbonLicenseMaintenance);
addIcon('carbon:query', carbonQuery);
addIcon('fluent-mdl2:product-release', fluentMd2ProductRelease);
addIcon('fluent-mdl2:box-search-16-regular', fluentBoxSearch16Regular);
addIcon('icon-park-outline:consume', iconParkOutlineConsume);
addIcon('majesticons:extensive-prescription', majesticonsExtensivePrescription);
addIcon('carbon:result', carbonResult);
addIcon('mdi:file-sign', mdiFileSign);
addIcon('mdi:receipt-text-send', mdiReceiptTextSend);
addIcon('ant-design:windows-outlined', antdWindowsOutlined);
addIcon('ant-design:folder-open-twotone', antdFolderOpenTwotone);
addIcon('ant-design:barcode-outlined', antdBarcodeOutlined);
addIcon('carbon:search', carbonSearch);
addIcon('lucide:table-2', lucideTable2);
addIcon('ant-design:export-outlined', antdExportOutlined);
addIcon('carbon:chart-bar-target', carbonChartBarTarget);
addIcon('carbon:building-insights-1', carbonBuildingInsights1);
addIcon('carbon:text-link', carbonTextLink);
